#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""
Título: Práctica 2 - Decodififador Lempel-Ziv.
Descripción: Implementar el decodificador Lempel-Ziv donde cada símbolo a 
             codificar desde un archivo en binario es de 16 bits
Autor: Erik Juárez Guerrero
Fecha de creación: 17 de marzo 2023
Última fecha de edición: 1 de abril 2023
Entrada: nombre de un archivo binario introducido por línea de mandos:
Salida: Genera dos archivos:
        * archivo codificado con extención ".lpz"
        * archivo que contiene el diccionario para decodificar el archivo 
          con extención ".dict"
Como usar: introducir en la consola o simbolo de sistema la instrucción:
           
           $ python .\decodificador_lempel_ziv.py .\[nombre_de_archivo]
"""

# Modulos Paquetes Bibliotecas
# ----------------------------
import argparse
import os
import pickle
import time


# Clases
# ------
class LZ:
    """Decodifica (descomprime) un archivo binario."""

    def __init__(self, path: str) -> None:
        self.path = path
        self.file_name , self.ext = os.path.splitext(self.path)
        self.out_fn = None
        self.file_dict = self.file_name + "_lpz.dict"
        self.decode_dict = {}
        self.padding = 0
        self.last_symbol = False

    def decompress(self):
        """Hace la compresión"""
        self.__unpickle()
        self.__read_file()
    
    def __hex_to_bin(self, byte):
        """pass"""
        bin_str = bin(byte)[2:]
        if len(bin_str) < 8:
            zeros = "0" * (8 - len(bin_str))
            bin_str = zeros + bin_str
        return bin_str

    def __read_file(self):
        """Lectura de archivo."""
        bit_str = ""
        bin_code = ""
        byte_output = bytearray()
        byte_counter = 0

        with open(self.path, "rb") as file, open(self.out_fn, "wb") as out_file:
            for byte_ in file.read():
                bit_str += self.__hex_to_bin(byte_)
                byte_counter += 1

                if byte_counter % 2 == 0:
                    bin_code += self.decode_dict[bit_str]
                    bit_str = ""

                while len(bin_code) >= 8:
                    byte_output.append(int(bin_code[:8], 2))
                    bin_code = bin_code[8:]

            # agrega padding al final para completar 8 bits
            if len(bin_code) % 8 != 0:
                padding = 8 - len(bin_code)
                bin_code = bin_code + (padding * "0")
                byte_output.append(int(bin_code, 2))

            out_file.write(byte_output)


    def __unpickle(self):
        """Recupera el diccionario [codigo: símbolo] y la extención del 
        archivo original desde el archivo .dict.

        [str, int, str, dict[str: str]
        0: la extención original
        1: numero de ceros agregados al bytearray
        2: el diccionaraio para decodificar
        """
        with open(self.file_dict, "rb") as file:
            obj = pickle.load(file)

        self.ext = obj[0]
        self.padding = obj[1]
        self.decode_dict = obj[2]

        self.out_fn = self.file_name + "_lpz_decompressed" + self.ext


# Funciones
# ---------
def arguments_parser():
    """Recive el nombre del archivo a comprimir como argumento desde la línea 
    de mandos.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("file_name", type=str, default=None, help="Nombre del archivo a comprimir.")
    args = parser.parse_args()
    return args


# Función main
# ------------
def main():
    """ fucnón main"""
    print("Processing...")

    # Tiempo de inicio
    start_time = time.time()

    # Entrada:
    args = arguments_parser()
    input_file = str(args.file_name)

    # Decodificación del archivo
    o_huffman = LZ(input_file)
    o_huffman.decompress()

    # Cálculo de tiempo de ejecución:
    end_time = time.time()
    elapsed_time = (end_time - start_time)# * (10**3)
    print(f"Tiempo de ejecución: {elapsed_time:.4f}s.")

    print("Done.")


if __name__ == "__main__":
    main()
